apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeworker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: acmeworker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: acmeworker
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: acmeworker
          image: {{.Values.workerImage}}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true

      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"

---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: acmeworker
spec:
  type: ClusterIP
  selector:
    app: acmeworker
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
