apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{.Values.tenant.backendClientId}}
  name: {{.Values.tenant.backendServiceAccountName}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmebackend
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: acmebackend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: acmebackend
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{.Values.tenant.backendServiceAccountName}}
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: acmebackend
          image: {{.Values.backendImage}}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

          env:
            - name: SB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: backend-variables
                  key: sb-endpoint

          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true

      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: acmebackend
spec:
  type: ClusterIP
  selector:
    app: acmebackend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
